FIGURE_SIZE_DEFAULT = [15, 11]
SIZE = 100
CHART_EXTENSION = "png"
TITLE_FONT_SIZE = 28
COLORS = ['C0', 'C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8', 'C9']
COLOR_BLUE = '#7EA6D7'
COLOR_BLACK = 'black'
MARKERS = ['o', 's', 'D', '<', '>', '^', 'v', 'P', 'X', '*']
LINES = ['-', ':', '--', '-.', '-', ':', '--', '-.', '-', ':']
