### Send a POST request to create a chart
POST http://127.0.0.1:8000/chart
Content-Type: application/json

{
  "type": "msa2n3nestedchart",
  "description": "string",
  "config": {
    "title": "Test"
  },
  "project": "1f1f90e9-9820-4008-b850-571fd0d5740e",
  "step": "measure",
  "data": {
    "parts": [
      5,
      4,
      7,
      7,
      2,
      3,
      6,
      10,
      1,
      1,
      10,
      6,
      8,
      2,
      8,
      3,
      9,
      9,
      5,
      4,
      16,
      13,
      20,
      20,
      13,
      15,
      11,
      14,
      12,
      19,
      11,
      16,
      19,
      12,
      18,
      18,
      17,
      14,
      17,
      15,
      21,
      23,
      22,
      26,
      21,
      23,
      30,
      24,
      25,
      28,
      26,
      22,
      24,
      27,
      29,
      28,
      25,
      29,
      27,
      30
    ],
    "operators": [
      3,
      3,
      3,
      3,
      3,
      3,
      3,
      3,
      3,
      3,
      3,
      3,
      3,
      3,
      3,
      3,
      3,
      3,
      3,
      3,
      2,
      2,
      2,
      2,
      2,
      2,
      2,
      2,
      2,
      2,
      2,
      2,
      2,
      2,
      2,
      2,
      2,
      2,
      2,
      2,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1
    ],
    "values": [
      120.78,
      121.55,
      121.33,
      121.99,
      118.14,
      119.35,
      122.87,
      121.0,
      118.03,
      117.92,
      121.11,
      122.87,
      119.68,
      117.7,
      119.9,
      119.57,
      120.12,
      119.68,
      120.67,
      121.0,
      121.33,
      119.68,
      120.12,
      119.68,
      119.24,
      115.94,
      122.21,
      119.9,
      119.24,
      118.58,
      121.88,
      121.33,
      118.69,
      119.46,
      119.13,
      119.02,
      121.33,
      120.89,
      121.0,
      116.49,
      117.92,
      121.11,
      122.87,
      119.68,
      117.7,
      119.9,
      119.57,
      120.12,
      119.68,
      120.67,
      121.0,
      122.43,
      119.68,
      117.37,
      121.55,
      120.56,
      119.24,
      121.33,
      118.03,
      118.47
    ]
  }
}
