### Send a POST request to create a chart
POST http://127.0.0.1:8000/chart
Content-Type: application/json

{
  "type": "capabilitystudy",
  "description": "string",
  "config": {
    "title": "P chart",
    "acceptable_percent": 10,
    "subgroup_size": 20,
    "type": "pchart"
  },
  "project": "1f1f90e9-9820-4008-b850-571fd0d5740e",
  "step": "measure",
  "data": {
    "values": [
      1,
      2,
      1,
      1,
      0,
      2,
      1,
      0,
      0,
      0,
      0,
      2,
      1,
      2,
      0,
      0,
      2,
      0,
      3,
      0,
      0,
      1,
      0,
      0,
      0,
      1,
      1,
      0,
      0,
      1,
      1,
      0,
      1,
      1,
      0,
      0,
      0,
      0,
      1,
      2,
      1,
      1,
      2,
      1,
      0,
      1,
      0,
      1,
      2,
      1,
      4,
      3,
      2,
      0,
      1,
      1,
      0,
      1,
      0,
      3,
      1,
      1,
      0,
      0,
      0,
      1,
      0,
      1,
      1,
      0,
      0,
      2,
      2,
      2,
      2,
      3,
      2,
      1,
      0,
      1,
      1,
      2,
      0,
      1,
      2,
      2,
      0,
      0,
      0,
      3,
      0,
      4,
      1,
      0,
      1,
      2,
      0,
      1,
      0,
      1
    ]
  }
}
