### Send a POST request to create a chart
POST http://127.0.0.1:8000/chart
Content-Type: application/json

{
  "type": "capabilitystudy",
  "description": "string",
  "config": {
    "title": "Normal",
    "reference": "100"
  },
  "project": "1f1f90e9-9820-4008-b850-571fd0d5740e",
  "step": "measure",
  "data": {
    "values": [
      2, 11, 3, 8, 6, 4, 3, 1, 9, 8, 6, 6, 5, 7, 4, 4, 8, 5, 7, 3, 9, 4, 2, 5, 4, 2, 6, 7, 9, 2,
      7, 5, 5, 4, 2, 5, 4, 6, 5, 3, 9, 9, 5, 8, 6, 4, 4, 9, 4, 8, 4, 3, 7, 6, 3, 2, 2, 3, 6, 6,
      6, 1, 11, 7, 8, 3, 5, 1, 5, 9, 5, 2, 3, 2, 7, 6, 6, 6, 11, 5, 3, 3, 10, 3, 4, 3, 2, 0, 7, 5,
      3, 3, 3, 4, 5, 6, 6, 4, 4, 5
    ]
  }
}
